language: python
python:
  - "2.6"
  - "2.7"
  # Coverage.py doesn't support Python 3.2 and so do we
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -e .
  - pip install pytest-cov
script:
  - py.test --cov=euclid --cov-report=
after_success:
  - bash <(curl -s https://codecov.io/bash)
