# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'light_source_settings.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from add_new_ls import *
from win32api import GetSystemMetrics

class Light_Source_Settings(QtWidgets.QWidget):
	def __init__(self):
		QtWidgets.QWidget.__init__(self)
		self.setupUi()
		self.setGeometry(GetSystemMetrics(0) - 325, 38, 325, GetSystemMetrics(1))
		self.new_ls = None
		self.pushButton_add_new.clicked.connect(self.add_new)		
		
	def setupUi(self):
		self.setObjectName("Form")
		self.resize(325, 855)
		self.gridLayoutWidget = QtWidgets.QWidget(self)
		self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 641))
		self.gridLayoutWidget.setObjectName("gridLayoutWidget")
		self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
		self.gridLayout.setContentsMargins(0, 0, 0, 0)
		self.gridLayout.setObjectName("gridLayout")
		self.minimap = QtWidgets.QGraphicsView(self.gridLayoutWidget)
		self.minimap.setObjectName("minimap")
		self.gridLayout.addWidget(self.minimap, 1, 0, 1, 1)
		self.pushButton_add_new = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.pushButton_add_new.setObjectName("pushButton_add_new")
		self.gridLayout.addWidget(self.pushButton_add_new, 2, 0, 1, 1)
		self.label = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label.setObjectName("label")
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.gridLayout_3 = QtWidgets.QGridLayout()
		self.gridLayout_3.setObjectName("gridLayout_3")
		self.doubleSpinBox_ypos_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_ypos_2.setMaximum(1.0)
		self.doubleSpinBox_ypos_2.setSingleStep(0.1)
		self.doubleSpinBox_ypos_2.setProperty("value", 0.5)
		self.doubleSpinBox_ypos_2.setObjectName("doubleSpinBox_ypos_2")
		self.gridLayout_3.addWidget(self.doubleSpinBox_ypos_2, 1, 4, 1, 1)
		self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_7.setObjectName("label_7")
		self.gridLayout_3.addWidget(self.label_7, 1, 3, 1, 1)
		self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_8.setMaximumSize(QtCore.QSize(16777215, 16770000))
		self.label_8.setObjectName("label_8")
		self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 5)
		self.doubleSpinBox_xpos_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_xpos_2.setMaximum(1.0)
		self.doubleSpinBox_xpos_2.setSingleStep(0.1)
		self.doubleSpinBox_xpos_2.setProperty("value", 0.5)
		self.doubleSpinBox_xpos_2.setObjectName("doubleSpinBox_xpos_2")
		self.gridLayout_3.addWidget(self.doubleSpinBox_xpos_2, 1, 2, 1, 1)
		self.doubleSpinBox_pow_2 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_pow_2.setMaximum(1.0)
		self.doubleSpinBox_pow_2.setSingleStep(0.1)
		self.doubleSpinBox_pow_2.setProperty("value", 1.0)
		self.doubleSpinBox_pow_2.setObjectName("doubleSpinBox_pow_2")
		self.gridLayout_3.addWidget(self.doubleSpinBox_pow_2, 2, 4, 1, 1)
		self.spinBox_ppf_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
		self.spinBox_ppf_2.setMaximum(2048)
		self.spinBox_ppf_2.setProperty("value", 512)
		self.spinBox_ppf_2.setObjectName("spinBox_ppf_2")
		self.gridLayout_3.addWidget(self.spinBox_ppf_2, 2, 2, 1, 1)
		self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_9.setObjectName("label_9")
		self.gridLayout_3.addWidget(self.label_9, 2, 3, 1, 1)
		self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_10.setObjectName("label_10")
		self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 2)
		self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_11.setObjectName("label_11")
		self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 2)
		self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_17.setObjectName("label_17")
		self.gridLayout_3.addWidget(self.label_17, 3, 0, 1, 1)
		self.horizontalSlider = QtWidgets.QSlider(self.gridLayoutWidget)
		self.horizontalSlider.setMinimum(380)
		self.horizontalSlider.setMaximum(780)
		self.horizontalSlider.setSingleStep(10)
		self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSlider.setObjectName("horizontalSlider")
		self.gridLayout_3.addWidget(self.horizontalSlider, 3, 2, 1, 3)
		self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_18.setObjectName("label_18")
		self.gridLayout_3.addWidget(self.label_18, 3, 1, 1, 1)
		self.pushButton_mod_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.pushButton_mod_6.setObjectName("pushButton_mod_6")
		self.gridLayout_3.addWidget(self.pushButton_mod_6, 4, 3, 1, 2)
		self.pushButton_mod_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.pushButton_mod_7.setObjectName("pushButton_mod_7")
		self.gridLayout_3.addWidget(self.pushButton_mod_7, 4, 0, 1, 3)
		self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)
		self.gridLayout_4 = QtWidgets.QGridLayout()
		self.gridLayout_4.setObjectName("gridLayout_4")
		self.doubleSpinBox_ypos_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_ypos_3.setMaximum(1.0)
		self.doubleSpinBox_ypos_3.setSingleStep(0.1)
		self.doubleSpinBox_ypos_3.setProperty("value", 0.5)
		self.doubleSpinBox_ypos_3.setObjectName("doubleSpinBox_ypos_3")
		self.gridLayout_4.addWidget(self.doubleSpinBox_ypos_3, 1, 4, 1, 1)
		self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_12.setObjectName("label_12")
		self.gridLayout_4.addWidget(self.label_12, 1, 3, 1, 1)
		self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_13.setMaximumSize(QtCore.QSize(16777215, 16770000))
		self.label_13.setObjectName("label_13")
		self.gridLayout_4.addWidget(self.label_13, 0, 0, 1, 5)
		self.doubleSpinBox_xpos_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_xpos_3.setMaximum(1.0)
		self.doubleSpinBox_xpos_3.setSingleStep(0.1)
		self.doubleSpinBox_xpos_3.setProperty("value", 0.5)
		self.doubleSpinBox_xpos_3.setObjectName("doubleSpinBox_xpos_3")
		self.gridLayout_4.addWidget(self.doubleSpinBox_xpos_3, 1, 2, 1, 1)
		self.doubleSpinBox_pow_3 = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget)
		self.doubleSpinBox_pow_3.setMaximum(1.0)
		self.doubleSpinBox_pow_3.setSingleStep(0.1)
		self.doubleSpinBox_pow_3.setProperty("value", 1.0)
		self.doubleSpinBox_pow_3.setObjectName("doubleSpinBox_pow_3")
		self.gridLayout_4.addWidget(self.doubleSpinBox_pow_3, 2, 4, 1, 1)
		self.spinBox_ppf_3 = QtWidgets.QSpinBox(self.gridLayoutWidget)
		self.spinBox_ppf_3.setMaximum(2048)
		self.spinBox_ppf_3.setProperty("value", 512)
		self.spinBox_ppf_3.setObjectName("spinBox_ppf_3")
		self.gridLayout_4.addWidget(self.spinBox_ppf_3, 2, 2, 1, 1)
		self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_14.setObjectName("label_14")
		self.gridLayout_4.addWidget(self.label_14, 2, 3, 1, 1)
		self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_15.setObjectName("label_15")
		self.gridLayout_4.addWidget(self.label_15, 1, 0, 1, 2)
		self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_16.setObjectName("label_16")
		self.gridLayout_4.addWidget(self.label_16, 2, 0, 1, 2)
		self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_19.setObjectName("label_19")
		self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
		self.horizontalSlider_2 = QtWidgets.QSlider(self.gridLayoutWidget)
		self.horizontalSlider_2.setMinimum(380)
		self.horizontalSlider_2.setMaximum(780)
		self.horizontalSlider_2.setSingleStep(10)
		self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
		self.horizontalSlider_2.setObjectName("horizontalSlider_2")
		self.gridLayout_4.addWidget(self.horizontalSlider_2, 3, 2, 1, 3)
		self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
		self.label_20.setObjectName("label_20")
		self.gridLayout_4.addWidget(self.label_20, 3, 1, 1, 1)
		self.pushButton_mod_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.pushButton_mod_8.setObjectName("pushButton_mod_8")
		self.gridLayout_4.addWidget(self.pushButton_mod_8, 4, 3, 1, 2)
		self.pushButton_mod_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
		self.pushButton_mod_9.setObjectName("pushButton_mod_9")
		self.gridLayout_4.addWidget(self.pushButton_mod_9, 4, 0, 1, 3)
		self.gridLayout.addLayout(self.gridLayout_4, 4, 0, 1, 1)
	
		self.retranslateUi()
	
	def retranslateUi(self):
		_translate = QtCore.QCoreApplication.translate
		self.setWindowTitle(_translate("Form", "Light Source Settings"))
		self.pushButton_add_new.setText(_translate("Form", "Add new"))
		self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Light Sources</span></p></body></html>"))
		self.label_7.setText(_translate("Form", "  y  "))
		self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Light source #n</span></p></body></html>"))
		self.label_9.setText(_translate("Form", "Power"))
		self.label_10.setText(_translate("Form", "  x  "))
		self.label_11.setText(_translate("Form", "Photons per frame"))
		self.label_17.setText(_translate("Form", "Wavelength"))
		self.label_18.setText(_translate("Form", "num"))
		self.pushButton_mod_6.setText(_translate("Form", "Delete"))
		self.pushButton_mod_7.setText(_translate("Form", "Modify"))
		self.label_12.setText(_translate("Form", "  y  "))
		self.label_13.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt;\">Light source #n</span></p></body></html>"))
		self.label_14.setText(_translate("Form", "Power"))
		self.label_15.setText(_translate("Form", "  x  "))
		self.label_16.setText(_translate("Form", "Photons per frame"))
		self.label_19.setText(_translate("Form", "Wavelength"))
		self.label_20.setText(_translate("Form", "num"))
		self.pushButton_mod_8.setText(_translate("Form", "Delete"))
		self.pushButton_mod_9.setText(_translate("Form", "Modify"))
	
	def closeEvent(self, event):
		if self.new_ls is not None:
			self.new_ls.closeEvent(event)
		self.close()
		
	def add_new(self):
		self.new_ls = Add_New_LS()
		self.new_ls.show()